# This is a basic workflow to help you get started with Actions

name: Test-Internet

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    runs-on: windows-latest
    steps:
      - name: Ping-Google
        run: ping google.com
      - name: Ping-Facebook
        run: ping facebook.com
      - name: Ping-Youtube
        run: ping youtu.be
