# This is a basic workflow to help you get started with Actions

name: TestGA

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line scri[t
        run: echo Hello, world!
      - name: Print information
        run: |
          uname -a
          dmesg
          pwd
          ifconfig
  test2:
    runs-on: windows-latest
    steps:
      - name: Something
        run: |
          ver
          ipconfig
          net user
