# This is a basic workflow to help you get started with Actions

name: Test-Internet

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    runs-on: windows-latest
    steps:
      - name: Ping-Google
        run: ping www.google.com
      - name: Ping-Facebook
        run: ping www.facebook.com
      - name: Ping-Youtube
        run: ping www.youtu.be
  test2:
    runs-on: windows-latest
    steps:
      - name: Ping-Microsoft
        run: ping bing.com
      - name: Ping-Cloudflare
        run: ping 1.1.1.1
  ipconfig:
    runs-on: windows-latest
    steps:
      - name: Query
        run: ipconfig
